# Generated by Django 4.1.5 on 2023-01-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FineSheetForm',
            fields=[
                ('Comments', models.TextField()),
                ('Date', models.DateField()),
                ('FineSheetID', models.AutoField(primary_key=True, serialize=False)),
                ('FineSheetAmount', models.IntegerField()),
                ('FineSheetReason', models.TextField()),
                ('MeetingDate', models.DateField()),
                ('MeetingType', models.CharField(choices=[('0', 'General'), ('1', 'SubSystem'), ('2', 'Worksession'), ('3', 'System'), ('4', 'Other')], default='4', max_length=1)),
                ('Status', models.CharField(choices=[('0', 'Unpaid'), ('1', 'Paid'), ('2', 'Pending_Verification')], default='2', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryForm',
            fields=[
                ('Comments', models.TextField()),
                ('Date', models.DateField()),
                ('Status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=1)),
                ('EquipmentID', models.AutoField(primary_key=True, serialize=False)),
                ('EquipmentName', models.CharField(max_length=255)),
                ('EquipmentDescription', models.TextField()),
                ('EquipmentQuantity', models.IntegerField()),
                ('EquipmentType', models.CharField(max_length=255)),
                ('EquipmentPrice', models.IntegerField()),
                ('Purpose', models.TextField()),
                ('VendorDetials', models.TextField()),
                ('ProjectName', models.CharField(max_length=255)),
                ('SubSystemName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('Comments', models.TextField()),
                ('Date', models.DateField()),
                ('Status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', max_length=1)),
                ('LeaveID', models.AutoField(primary_key=True, serialize=False)),
                ('MeetingDate', models.DateField()),
                ('MeetingType', models.CharField(choices=[('0', 'General'), ('1', 'SubSystem'), ('2', 'Worksession'), ('3', 'System'), ('4', 'Other')], default='4', max_length=1)),
                ('Reason', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
