# Generated by Django 4.1.5 on 2023-01-28 21:32

from django.conf import settings
from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='SATLAB_USER',
            field=models.ForeignKey(on_delete=models.SET(forms.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryform',
            name='SATLAB_USER',
            field=models.ForeignKey(on_delete=models.SET(forms.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finesheetform',
            name='MembersFined',
            field=models.ManyToManyField(related_name='MembersFined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finesheetform',
            name='SATLAB_USER',
            field=models.ForeignKey(on_delete=models.SET(forms.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
