export interface UserProfile {
  id: string,
  username: string,
  first_name: string,
  last_name: string,
  email: string,
  dept: string,
  mobileNumber: string, 
  degree: string, 
  year: string, 
  alternateEmail: string,
  subSystem: string, 
  presentSystem: string, 
  Experience: string,
  topicWorkingOn: string, 
  profilePic: string, 
  hobbies: string, 
  softwaresKnown: string,
}
