# Generated by Django 4.1.5 on 2023-01-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_description', models.TextField()),
                ('is_read_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reacton_date', models.DateTimeField(auto_now_add=True)),
                ('reaction', models.CharField(choices=[('0', 'like'), ('1', 'dislike'), ('2', 'love'), ('3', 'haha'), ('4', 'wow'), ('5', 'sad'), ('6', 'angry')], default='like', max_length=1)),
                ('group_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grouppost')),
            ],
        ),
    ]
